### ISSUE TITLE
keyboard, mouse and rawDevice constructors changed on USB Host example

### ISSUE THREAD

**Issue by WebGE** [ghi-electronics/Documentation#131]
I replaced :
var keyboard = new Keyboard(e.Id);
var mouse = new Mouse(e.Id);
var rawDevice = new RawDevice(e.Id);

by :
var keyboard = new Keyboard(e.Id,e.InterfaceIndex);
var mouse = new Mouse(e.Id,e.InterfaceIndex);
var rawDevice = new RawDevice(e.Id,e.InterfaceIndex,e.Type);

**Comment by gus-ghielec** [comment]
This is already fixed in dev branch, thanks. Please check
