### ISSUE TITLE
Secure Assemblies

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/Documentation#170]
update external flash section on https://docs.ghielectronics.com/software/tinyclr/tutorials/external-memory.html page.

Remove the code showing direct read write and instead explain how 8MBytes out of the 16MByte external flash is used for Deployment, just like the internal secure deployment. Since QSPI is not secure, a hacker can just pull out and read, we have "Secure" flag you can add to AssemblyInfo which tells the system that this specific assembly must be in the internal secure flash. The system will automatically locate assemblies and will try to put everything in the internal flash but when teh internal flash is full, it will start moving assemblies not marked as "Secure" to external memory, if available.

There is a flag to enable External flash that can be set in software or set using TinyCLR Config tool. Even if QSPI is found, the system will not use it till the user opt in.

We support 2 specific part numbers, document part numbers. If a customer is add their own QSPI then need one of the 2 we have tested.

Visual Studio clearly shows what assemblies are secure when deploying.

Finally, the other 8 MByte of flash is now reserved for future use.

**Comment by JoelGHI** [comment]
Fixed via #191 and #194
