### ISSUE TITLE
Add details on parameters for StorageController.QuadSpi methods

### ISSUE THREAD

**Issue by ghost** [ghi-electronics/Documentation#276]
There are confusion between sectors, blocks or bytes in the different methods.

See [this discussion](https://forums.ghielectronics.com/t/click-drivers-from-mbn/23009/48) or [this one](https://forums.ghielectronics.com/t/tfs-driver-s/23196/3), for example.

**Comment by Palomino34** [comment]
StorageController uses (long address) in bytes in all their API.

There is no Sector, Block.
