### ISSUE TITLE
Provide default USB PID 

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/Documentation#351]
GHI will provide a default (and licensed for commercial use) USB PIDs for CDC and WinUSB usage on GHI's SITCore products. The library should just include them internally but the user can override them if they need. The customer should NOT modify the PID unless they are modifying the VID to what they own or they are licensed to use. This must be very clear in the docs.

GHI VID 0x1B9F
GHI licensed CDC PID 0xF001
GHI licensed WinUSB PID 0xF002

**Comment by Palomino34** [comment]
GHI VID 0x1B9F

USBClient PID:
Mouse = 0xF000,
CDC = 0xF001,
MassStorage = 0xF002,
Keyboard = 0xF004,
Joystick = 0xF005,
WinUsb = 0xF006,

Bootloader 2.x PID:
0x0104

TinyCLR 2.x PID:
0x5010

**Comment by Palomino34** [comment]
Update:

GHI VID 0x1B9F

USBClient PID:
Mouse = 0xF000,
CDC = 0xF001,
MassStorage = 0xF002,
Keyboard = 0xF004,
Joystick = 0xF005,
WinUsb = 0xF006,
RawDevice= 0xF007,


Bootloader 2.x PID:
0x0104

TinyCLR 2.x PID:
0x5010
