### ISSUE TITLE
Fix network IP address even check

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/Documentation#404]
```
if (address[0] != 0 && address[1] != 0 && address[2] != 0 && address[3] != 0)
                LinkReady = true;

```

should be changed to 

```
if (address[0] != 0 || address[1] != 0 || address[2] != 0 || address[3] != 0)
                LinkReady = true;

```

**Comment by poundy** [comment]
how will this work if the most universal address space is used on a home network, 192.168.0.x, when the device gets an address of 192.168.0.14 ?

**Comment by gus-ghielec** [comment]
Zero is allowed in the IP address but they shouldn't all be zero

**Comment by poundy** [comment]
oh yeah. I should have checked the logic better, it's clear if any is non-zero then the link address has changed - in fact the problem i describe is the reason the original code didn't work

**Comment by greg-norris** [comment]
Should this be fixed on DOCS or LIBS?

**Comment by gus-ghielec** [comment]
didn't find this anywhere on docs!
