### ISSUE TITLE
Supported SPI clocks

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/Documentation#405]
Add a note on SPI explaining the supported clocks and how they are derived from max frequency. If max frequency is 60Mhz then the clocks are 60 -> 30 -> 20 ....etc 1/2 -> 1/3 -> 1/4 The driver will pick the closet clock below the selected one. Setting the clock on previous example to 29 will result in 20 not 30. This is done on purpose to keep the clock the highest possible but at or below the specified frequency, never higher.

**Comment by greg-norris** [comment]
Made changes to documentation that need to be reviewed before final pull request submission.
