### ISSUE TITLE
SCM20100E SPI Ports Documentation

### ISSUE THREAD

**Issue by skeller2015** [ghi-electronics/Documentation#407]
The SOM table on the https://docs.ghielectronics.com/hardware/sitcore/som.html page where it lists the peripherals for each SOM, the SCM20100E shows 3 SPI ports.  According to the pinout, there are 2 full, SPI3, SPI4, and a partial, SPI6.  I am not sure how useful SPI6 could be with only CLK and MISO but maybe there is a use.  Either way, I think the table should reflect the distinction in some way.  Or is pin-out wrong and SPI6 MOSI is not documented?

**Comment by Palomino34** [comment]
PA7 (SPI6 - Mosi) is used for Ethernet. Document should be updated. 

Thankks.

**Comment by greg-norris** [comment]
Fixed in DOCS, need to discuss before submitting PR.
