### ISSUE TITLE
Community forum suggestion

### ISSUE THREAD

**Issue by skeller2015** [ghi-electronics/Documentation#408]
Admittedly this is purely very low on the list and I hesitate to bring it up since it is purely for convenience sake.  Would it be possible, at the top of the main Community Forum page, to put links directly to the Documents page and the GitHub page?  It would save some clicking around that I seem to always be doing to get to those pages.

**Comment by greg-norris** [comment]
Added to the Menu

**Comment by skeller2015** [comment]
Well, hot dang!  Thanks for adding those!
