### ISSUE TITLE
Upgrade to SITCore is wrong

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/Documentation#412]
The description of upgrading from G30 and G80 are backwards and need reworking. SITCore SC100 is LQFP100, similar to G80, not LQFP64.

**Comment by gus-ghielec** [comment]
here is more info
[SC20100SvsG80.pdf](https://github.com/ghi-electronics/Documentation/files/5810649/SC20100SvsG80.pdf)

**Comment by greg-norris** [comment]
Made changes to documentation that need to be reviewed before final pull request submission.
