### ISSUE TITLE
Wake up pin future is not documented correctly

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/Documentation#420]

**Comment by gus-ghielec** [comment]
Only falling edges are supported today. We either need to fix the software to support rising edges, or update the docs to clarify.

**Comment by gus-ghielec** [comment]
Next release is going to fix wakeup pin to wakeup on rising edge. The design should include an external pull down resistor.

**Comment by gus-ghielec** [comment]
A property was added to enable both, high or low

**Comment by greg-norris** [comment]
Updated in PR #456
