### ISSUE TITLE
Recheck CAN filter statement

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/Documentation#449]
CAN page
Verify this statement: "SITCore hardware supports up to 128 filter slots; however, each extended ID uses 2 slots."

There are 64 filters for Extid and 128 filters for StdId, shared by both 2 CAN.

**Comment by gus-ghielec** [comment]
This wrong and needs to be corrected. Each CAN channel has up to 64 standard IDs and 32 Extended IDs.

**Comment by greg-norris** [comment]
Fixed in PR #452
