### ISSUE TITLE
ENC28J60 documentation has incorrect controller name

### ISSUE THREAD

**Issue by martincalsyn** [ghi-electronics/Documentation#463]
Documentation at : https://docs.ghielectronics.com/software/tinyclr/tutorials/ethernet.html

Documentation says:
    var networkController = NetworkController.FromName
        ("ENC28J60.NetworkController");

Should be:
    var networkController = NetworkController.FromName(@"GHIElectronics.TinyCLR.NativeApis.ENC28J60.NetworkController\0");

**Comment by greg-norris** [comment]
Fixed in PR #466
