### ISSUE TITLE
IFU 2.1 to 2.2

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/Documentation#493]
IFU needs a new section. This needs to be tested!

# IFU 2.0 to 2.1
Starting release 2.1, IFU is reworked to support complete firmware and application update using external flash (when available) or external RAM (when available). Unfortunately, using IFU to update from 2.1 to 2.2 is only possible if the deployment region was not extended to use external flash. 

A work around to update 2.0 to 2.1 is by update 2.0 to a new 2.1 temporarily application that does not use external flash. Once this temp application is loaded then the final application with external flash can be deployed.

**Comment by Palomino34** [comment]
Tested from 2.0 (2.0.08000) to 2.1.0-preview4.
