### ISSUE TITLE
TLS Tutorial uses outdated Browser

### ISSUE THREAD

**Issue by AndreMarschalek** [ghi-electronics/Documentation#504]
the sample use Microsoft Edge Legacy and should be updated to Microsoft Edge

[Lifecycle FAQ](https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge) 

for your convenience i have attached the required screenshots

[TLS_Client_Steps.zip](https://github.com/ghi-electronics/Documentation/files/6135081/TLS_Client_Steps.zip)

**Comment by greg-norris** [comment]
Fixed in PR #511
