### ISSUE TITLE
GPIO Lowlevel note

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/Documentation#529]
CAN => Work after Open Controller
DMCI => Work after Open Controller
QSPI => Work after Open controller
SDcard => Work after open controller
SPI => Work after open controller
I2C => Work after Open Controller

PWM => Work after Enable Channel

Uart => work after SetActiveSetting
Display Native => Work after SetActiveSetting

**Comment by greg-norris** [comment]
Fixed in PR #548
