### ISSUE TITLE
Check network tutorial

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/Documentation#535]
https://forums.ghielectronics.com/t/is-tutorial-networking-interfaces-wifi-still-up-to-date-for-tinyclr-v2-1-0-preview-4/23711

**Comment by gus-ghielec** [comment]
no issue found

**Comment by gus-ghielec** [comment]
however we can change the string to use the "pins" NuGet as this is the proper use

**Comment by greg-norris** [comment]
Updated in PR #537
