### ISSUE TITLE
screen size on graphics demo

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/Documentation#542]
Is this correct? `st7735.SetDrawWindow(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT);` Should not this be `st7735.SetDrawWindow(0, 0, SCREEN_WIDTH-1, SCREEN_HEIGHT-1);`

Either the demo is wrong or the driver needs fixing.

**Comment by greg-norris** [comment]
Fixed in PR #546
