### ISSUE TITLE
FEZ HAT Rev 1.1

### ISSUE THREAD

**Issue by xied75** [ghi-electronics/Documentation#577]
Hi guys,

So glad to find your repos here. I just found a FEZ HAT Rev 1.1 out of thin air. I see there is PDF for the Rev 1.2, do you happen to have one for the Rev 1.1?

Related question: can this thing work with other random devices or it must be the RPi2B under Windows 10?

Sorry for the archaeology style, but I guess this is the true spirit of DIY? :)

Best regards,

Dong

**Comment by gus-ghielec** [comment]
This is from many years ago and everything we have is already provided. Sorry, we can't be of further help here but you should consider one of our active products and then we can give good support/answers.
