### ISSUE TITLE
update hashtable section

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/Documentation#583]
to  show https://docs.microsoft.com/en-us/dotnet/api/system.collections.hashtable?view=net-5.0

```
// If a key does not exist, setting the default Item property
// for that key adds a new key/value pair.
openWith["doc"] = "winword.exe";
```

Change the code to something more relevant to hardware, like the code used for WebUSB https://github.com/ghi-electronics/TinyCLR-WebUSB/blob/main/WebUSBApp/WebUSBApp/Program.cs

**Comment by greg-norris** [comment]
Fixed with pull request #633
