### ISSUE TITLE
Add lable DAC2 on PA5 if the pin available.

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/Documentation#707]
I think any SITCore that PA5 available, we should add lable DAC2 as well.

Without DAC2 users think there is only one DAC1 available on PA4 and less option for them

![image](https://user-images.githubusercontent.com/15822304/197551177-0620a6fb-4af8-494f-9eae-eb002933af28.png)

**Comment by greg-norris** [comment]
Added to Pico & Flea in PR #708
